spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:database/db.changelog-master.yaml